[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render"
  status = 200
  force = true

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"